# Generated by Django 3.2.6 on 2021-08-13 16:26

import admin_api.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '城市',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '成员',
            },
        ),
        migrations.CreateModel(
            name='DemoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_bool', models.BooleanField(default=True, verbose_name='BooleanField')),
                ('field_char', models.CharField(max_length=10, verbose_name='CharField')),
                ('field_date', models.DateField(blank=True, null=True, verbose_name='DateField')),
                ('field_datetime', models.DateTimeField(blank=True, null=True, verbose_name='DateTimeField')),
                ('field_number', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='DecimalField')),
                ('field_duration', models.DurationField(blank=True, null=True, verbose_name='DurationField')),
                ('field_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='EmailField')),
                ('field_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='FileField')),
                ('field_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='ImageField')),
                ('field_int', models.IntegerField(blank=True, null=True, verbose_name='IntegerField')),
                ('field_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='GenericIPAddressField')),
                ('field_text', models.TextField(blank=True, null=True, verbose_name='TextField')),
                ('field_time', models.TimeField(blank=True, null=True, verbose_name='TimeField')),
                ('field_password', admin_api.fields.PasswordField(blank=True, max_length=100, null=True, verbose_name='密码')),
                ('field_m1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.city', verbose_name='ForeignKey')),
                ('field_m2', models.ManyToManyField(blank=True, to='myapp.Member', verbose_name='ManyToManyField')),
            ],
            options={
                'verbose_name': '字段演示',
            },
        ),
    ]
